[package]
name = "gul-tls"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "TLS/SSL support"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["tls", "ssl", "security"]

[dependencies]

[dev-dependencies]
