[package]
name = "gul-servo"
version = "0.1.0"
edition = "2021"

[features]
default = ["stub"]
stub = []
real = ["dep:rppal"]

[dependencies]
rppal = { version = "0.14", optional = true }
log = "0.4"
