[package]
name = "gul-postgres"
version = "0.1.0"
edition = "2021"

[features]
default = ["real"]
real = ["dep:sqlx"]
mock = []

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "postgres",
], optional = true }
log = "0.4"
