[package]
name = "gul-gpio"
version = "0.1.0"
edition = "2021"

[features]
default = ["stub"]
stub = []
real = ["dep:rppal"]

[dependencies]
rppal = { version = "0.14", optional = true }
embedded-hal = "1.0"
log = "0.4"

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-hal = "0.45.2"

[build-dependencies]
embuild = { version = "0.31.3", features = ["espidf"] }
