[package]
name = "gul-chem"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Chemistry tools"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["chemistry", "science"]

[dependencies]

[dev-dependencies]
