[package]
name = "gul-hash"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Hashing algorithms for GUL"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["hash", "crypto", "gul"]
categories = ["development-tools"]

[dependencies]

[dev-dependencies]
