[package]
name = "gul-pandas"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "DataFrame operations"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["pandas", "dataframe"]

[dependencies]

[dev-dependencies]
