[package]
name = "gul-sqlite"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "SQLite driver"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["sqlite", "database", "sql"]

[dependencies]

[dev-dependencies]
