[package]
name = "gul-sensors"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Sensor libraries"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["sensors", "hardware"]

[dependencies]

[dev-dependencies]
