[package]
name = "gul-dynamodb"
version = "0.1.0"
edition = "2021"
description = "DynamoDB Client for GUL"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
