[package]
name = "gul-i2c"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "I2C communication"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["i2c", "hardware", "embedded"]

[dependencies]
[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-hal = "0.45.2"

[dev-dependencies]
