[package]
name = "gul-table"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Terminal tables"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["table", "ui"]

[dependencies]

[dev-dependencies]
