[package]
name = "gul-math"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Advanced mathematics"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["math", "mathematics"]

[dependencies]

[dev-dependencies]
