[package]
name = "gul-batt"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
anyhow = "1.0"

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-hal = "0.45.2"
esp-idf-svc = "0.51.0"

[features]
default = ["std"]
std = []
