[package]
name = "gul-plot"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Plotting library"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["plot", "visualization"]

[dependencies]

[dev-dependencies]
