[package]
name = "gul-ui"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "UI framework"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["ui", "framework"]

[dependencies]

[dev-dependencies]
