[package]
name = "gul-editor"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Text editor TUI"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["editor", "text", "tui"]

[dependencies]

[dev-dependencies]
