[package]
name = "gul-explorer"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "File explorer TUI"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["explorer", "files", "tui"]

[dependencies]

[dev-dependencies]
