[package]
name = "gul-log"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Logging framework"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["logging", "log"]

[dependencies]

[dev-dependencies]
