[package]
name = "gul-devops"
version = "0.1.0"
edition = "2021"

[dependencies]
bollard = "0.13"
kube = "0.82"
k8s-openapi = { version = "0.18", features = ["v1_20"] }
opentelemetry = "0.18"
uuid = { version = "1.0", features = ["v4"] }
