[package]
name = "gul-udp"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "UDP socket support"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["udp", "sockets", "networking"]

[dependencies]

[dev-dependencies]
