[package]
name = "gul-motors"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Motor control"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["motors", "hardware"]

[dependencies]

[dev-dependencies]
