[package]
name = "gul-signal"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Signal processing"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["signal", "dsp"]

[dependencies]

[dev-dependencies]
