[package]
name = "gul-debugger"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Debugger TUI"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["debugger", "debug", "tui"]

[dependencies]

[dev-dependencies]
