[package]
name = "gul-websocket"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "WebSocket support"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["websocket", "realtime"]

[dependencies]

[dev-dependencies]
