[package]
name = "gul-html"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "HTML templating"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["html", "template"]

[dependencies]

[dev-dependencies]
