[package]
name = "gul-ros"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "ROS integration"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["ros", "robotics"]

[dependencies]

[dev-dependencies]
