[package]
name = "gul-storage-embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-svc = "0.51.0"
esp-idf-hal = "0.45.2"
embedded-svc = "0.27"
