[package]
name = "gul-test"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Testing framework for GUL"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["test", "testing", "framework", "gul"]
categories = ["development-tools::testing"]

[dependencies]

[dev-dependencies]
