[package]
name = "gul-colors"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Terminal colors"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["colors", "terminal"]

[dependencies]

[dev-dependencies]
