[package]
name = "gul-display"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8"
display-interface = "0.4"
display-interface-spi = "0.4"
mipidsi = "0.7"               # Drivers for ST7789 etc.
[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-svc = "0.51.0"
esp-idf-hal = "0.45.2"
