[package]
name = "gul-mock"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Mocking framework"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["mock", "testing"]

[dependencies]

[dev-dependencies]
