[package]
name = "gul-camera"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-hal = "0.2"
libc = "0.2.178"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "espidf")'.dependencies]
esp-idf-svc = "0.51.0"
esp-idf-sys = "0.36.1"
