[package]
name = "gul-bio"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Bioinformatics"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["bioinformatics", "biology"]

[dependencies]

[dev-dependencies]
