[package]
name = "gul-orm"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "ORM framework"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["orm", "database"]

[dependencies]

[dev-dependencies]
