[package]
name = "gul-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
chrono = "0.4"
base64 = "0.21"
hmac = "0.12"
sha2 = "0.10"
