[package]
name = "gul-bench"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Benchmarking"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["benchmark", "performance"]

[dependencies]

[dev-dependencies]
