[package]
name = "gul-stats"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Statistics library"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["statistics", "math"]

[dependencies]

[dev-dependencies]
