[package]
name = "gul-physics"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Physics simulations"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["physics", "simulation"]

[dependencies]

[dev-dependencies]
