[package]
name = "gul-tcp"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "TCP socket support"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["tcp", "sockets", "networking"]

[dependencies]

[dev-dependencies]
