[package]
name = "gul-dns"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "DNS resolution"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["dns", "network"]

[dependencies]

[dev-dependencies]
