[package]
name = "gul-redis"
version = "0.1.0"
edition = "2021"

[features]
default = ["real"]
real = ["dep:redis"]
mock = []

[dependencies]
redis = { version = "0.23", optional = true }
log = "0.4"
