[package]
name = "gul-compress"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "Compression library for GUL"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["compress", "zip", "gul"]
categories = ["development-tools"]

[dependencies]

[dev-dependencies]
