[package]
name = "gul-mongodb"
version = "0.1.0"
edition = "2021"
authors = ["GUL Team <team@gul-lang.org>"]
description = "MongoDB driver"
license = "MIT"
repository = "https://github.com/gul-lang/packages"
keywords = ["mongodb", "database", "nosql"]

[dependencies]

[dev-dependencies]
