[application]
name = "gul-website"
default_platform = "web"

[web.app]
title = "GUL - The Universal Programming Language"
base_path = "/"

[web.watcher]
watch_path = ["src", "public", "assets"]
reload_html = true
index_on_404 = true

[web.resource]
style = ["/style.css"]
script = []

[web.resource.dev]
style = ["/style.css"]
script = []

[[web.proxy]]
backend = "http://localhost:3000/api"
